ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # Enable inputs
    use_control: false

    # Input sensor data
    odom0: /odom
    odom0_config: [true, true, false,   # position x, y (not z)
                      false, false, false, # no orientation 
                      true, false, false,   # velocity x, y (not z)
                      false, false, true,  # only yaw velocity
                      false, false, false] # no acceleration

