slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping #localization
    use_sim_time: false

    #if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose

    #Make sure this is the correct path to the costmap initilazation 
    map_file_name: /root/ap4_hlc_docker_dir/ap4hlc_ws/src/autonomous_platform_robot_description_pkg/maps/gokart_empty_map

    map_start_pose: [69.0, 52.0, 0.0]
    map_start_at_dock: true

    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.1
    map_update_interval: 0.1 #0.1 # Faster updates
    resolution: 0.1 #0.05
    min_laser_range: 1.5  
    max_laser_range: 12.0  
    minimum_time_interval: 0.5
    transform_timeout: 0.1
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    enable_interactive_mode: true

    # Allow unknown areas to be mapped
    allow_unknown: true
    assume_unknown_space_as_free: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.3
    minimum_travel_heading: 0.3
    scan_buffer_size: 30
    scan_buffer_maximum_scan_distance: 12.0
    link_match_minimum_response_fine: 0.2 #0.1<-------------  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 6.0  
    do_loop_closing: true #<---------------- maybe set false
    loop_match_minimum_chain_size: 10           
    loop_match_maximum_variance_coarse: 3.0  
    loop_match_minimum_response_coarse: 0.3  
    loop_match_minimum_response_fine: 0.3 #0.2 <------------------- 

    # Correlation Parameters
    correlation_search_space_dimension: 0.2   #0.5<---------
    correlation_search_space_resolution: 0.01
    correlation_search_smin_pace_smear_deviation: 0.1 

    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5      #0.3    #<-------
    angle_variance_penalty: 1.0       #0.7      <---------------
    fine_search_angle_offset: 0.0175     
    coarse_search_angle_offset: 0.349   
    coarse_angle_resolution: 0.0175        
    minimum_angle_penalty: 0.7
    minimum_distance_penalty: 0.3
    use_response_expansion: true

    # Use odometry to map unknown areas
    use_odometry_guess: true

    
