<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length" value="0.01"/>
    <xacro:property name="lidar_radius" value="0.1"/>


    <link name="imu_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.1" length="${lidar_length}" radius="${lidar_radius}" >
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cylinder>

  </link>

    <joint name="base_imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 ${0.1+0.05+lidar_length/2.0}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
        <material>Gazebo/Red</material>
        <color rgba="1.0 0.0 0.0 1.0"/>
          <sensor name="imu_sensor" type="imu">
            <always_on>true</always_on>
            <update_rate>10</update_rate>
            <visualize>true</visualize>
            <topic>/imu</topic>
            <gz_frame_id>imu_link</gz_frame_id>
            <imu>
              <angular_velocity>
                <x>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    <bias_mean>0.0000075</bias_mean>
                    <bias_stddev>0.0000008</bias_stddev>
                  </noise>
                </x>
                <y>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    <bias_mean>0.0000075</bias_mean>
                    <bias_stddev>0.0000008</bias_stddev>
                  </noise>
                </y>
                <z>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>2e-4</stddev>
                    <bias_mean>0.0000075</bias_mean>
                    <bias_stddev>0.0000008</bias_stddev>
                  </noise>
                </z>
              </angular_velocity>
              <linear_acceleration>
                <x>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    <bias_mean>0.1</bias_mean>
                    <bias_stddev>0.001</bias_stddev>
                  </noise>
                </x>
                <y>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    <bias_mean>0.1</bias_mean>
                    <bias_stddev>0.001</bias_stddev>
                  </noise>
                </y>
                <z>
                  <noise type="gaussian">
                    <mean>0.0</mean>
                    <stddev>1.7e-2</stddev>
                    <bias_mean>0.1</bias_mean>
                    <bias_stddev>0.001</bias_stddev>
                  </noise>
                </z>
              </linear_acceleration>
            </imu>
          </sensor>
    </gazebo>
</robot>