<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ackermann_steering_robot">
  <xacro:include filename="$(find autonomous_platform_robot_description_pkg)/src/description/inertia_macros.xacro"/> 

  <link name="base_footprint">
  </link>

  <material name="custom_red">
    <ambient rgba="1.0 0.0 0.0 1.0"/> <!-- Red color -->
    <diffuse rgba="1.0 0.0 0.0 1.0"/> <!-- Red color -->
    <specular rgba="0.1 0.1 0.1 1.0"/> <!-- Slight reflection -->
  </material>

   <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_length" value="1.02"/>
  <xacro:property name="base_height" value="0.05"/>

  <!-- params -->
  <xacro:property name="wheel_radius" value="0.105"/>
  <xacro:property name="wheel_width" value="0.080"/>
  <xacro:property name="y_offset" value="${base_width/2 + 0.155}"/>

  <!-- Gokart front wing parameters - As of now simplified to a slab -->
  <xacro:property name="gokart_frontwing_width" value="0.8"/>
  <xacro:property name="gokart_frontwing_length" value="0.125"/>
  <xacro:property name="gokart_frontwing_height" value="0.025"/>
  <xacro:property name="gokart_frontwing_body_xoff" value="0.16"/>

  <!-- weights -->
  <xacro:property name="wheel_weight" value="1.5"/>
  <xacro:property name="chassi_body_weight" value="50.0"/>
  <xacro:property name="frontwing_weight" value="20.0"/>


  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Red">
          <color rgba="1.0 0.0 0.0 1.0"/>
        </material>
    </visual>

    <collision>
      <geometry>
        <box size="1 0.5 0.1"/>
      </geometry>
    </collision>

    <xacro:inertial_box mass="${chassi_body_weight}" x="1" y="0.5" z="0.1">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_box>

  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.1" rpy="0 0 0"/>
  </joint>

  <!-- Steering joints -->
  <joint name="left_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="left_swivel"/>
    <origin xyz="0.5 ${y_offset} 0.0" rpy="0 0  0"/>
    <axis xyz="0 0 1"/> <!-- Rotate around the Y-axis (steering axis) -->
    <limit effort="100" lower="${-pi/5}" upper="${pi/5}" velocity="5" />
  </joint>

  <joint name="right_steering_joint" type="revolute">
    <parent link="base_link"/>
    <child link="right_swivel"/>
    <origin xyz="0.5 ${-y_offset} 0.0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/> <!-- Rotate around the Y-axis (steering axis) -->
    <limit effort="100" lower="${-pi/5}" upper="${pi/5}" velocity="5" />
  </joint>

   <!-- front wheel rotating joints -->
  <joint name="left_steering_rotating_joint" type="continuous">
    <parent link="left_swivel"/>
    <child link="left_wheel_steering"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Rotate around the Y-axis (drive axis) -->
    <dynamics friction="0.1" damping="0.5" />
    <limit lower="${-pi}" upper="${pi}" effort="0.1" velocity="15" />
  </joint>

  <joint name="right_steering_rotating_joint" type="continuous">
    <parent link="right_swivel"/>
    <child link="right_wheel_steering"/>
    <origin xyz="-0.0 0.0 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Rotate around the Y-axis (drive axis) -->
    <dynamics friction="0.1" damping="0.5" />
    <limit lower="${-pi}" upper="${pi}" effort="0.1" velocity="15" />
  </joint>

  <!-- Drive joints -->
  <joint name="left_drive_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.5 ${y_offset} 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Rotate around the Y-axis (drive axis) -->
    <dynamics friction="0.1" damping="0.5" />
    <limit lower="${-pi}" upper="${pi}" effort="70" velocity="15" />
  </joint>

  <joint name="right_drive_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.5 ${-y_offset} 0.0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Rotate around the Y-axis (drive axis) -->
    <dynamics friction="0.1" damping="0.5" />
    <limit lower="${-pi}" upper="${pi}" effort="70" velocity="15" />
  </joint>


  <!-- Steering swiwels -->
  <link name="left_swivel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.005"/>
      </geometry>
      <material name="custom_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.005"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="0.005" radius="0.05">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_swivel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.005"/>
      </geometry>
      <material name="custom_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.005"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="0.005" radius="0.05">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <!-- Steering wheels -->
  <link name="left_wheel_steering">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="custom_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_wheel_steering">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>

    <gazebo reference="right_wheel_steering">
      <material> Gazebo/Black </material>
    </gazebo> 
  </link>

  <!-- Driving wheels -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="custom_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="custom_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${wheel_weight}" length="${wheel_width}" radius="${wheel_radius}">
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    </xacro:inertial_cylinder>
  </link>


  <!-- Create frontwing link on which one would like to mount future sensors -->
  <link name="gokart_frontwing_link">
      <visual>
        <origin xyz="${gokart_frontwing_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
             <box size="${gokart_frontwing_length} ${gokart_frontwing_width} ${gokart_frontwing_height}"/>
        </geometry>
        <material name="Green">
          <color rgba="0 1.0 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="${gokart_frontwing_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
             <box size="${gokart_frontwing_length} ${gokart_frontwing_width} ${gokart_frontwing_height}"/>
        </geometry>
      </collision>

      <xacro:inertial_box mass="${frontwing_weight}" x="${gokart_frontwing_length}" y="${gokart_frontwing_width}" z="${gokart_frontwing_height}">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_box>
    </link>
 
  <!-- Create frontwing joint, mount the frontwing to the gokart body with a fixed joint -->
  <joint name="frontwing_joint" type="fixed">
      <parent link="base_link"/>
      <child link="gokart_frontwing_link"/>
      <origin xyz="${base_length/2+gokart_frontwing_body_xoff} 0 ${-gokart_frontwing_height}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
  </joint>

</robot>
