<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

 <!-- Heavily based on https://navigation.ros.org/setup_guides/urdf/setup_urdf.html -->
  
   <!-- Define robot constants -->
  <xacro:property name="chassi_width" value="0.4"/>
  <xacro:property name="chassi_length" value="1.02"/>
  <xacro:property name="chassi_height" value="0.05"/>

  <!-- backwheel params -->
  <xacro:property name="backwheel_radius" value="0.125"/>
  <xacro:property name="backwheel_width" value="0.069"/>
  <xacro:property name="backwheel_ygap" value="0.0"/>
  <xacro:property name="backwheel_zoff" value="-0.02"/>
  <xacro:property name="backwheel_xoff" value="${-(chassi_length)/2 + (backwheel_radius)}"/>
  
  <!-- frontwheel params -->
  <xacro:property name="frontwheel_radius" value="0.105"/>
  <xacro:property name="frontwheel_width" value="0.080"/>
  
  <!-- Frontwheel steering geometry params -->
  <xacro:property name="steering_arm_length" value="0.1"/>
  <xacro:property name="steering_arm_radius" value="0.015"/>
    <!-- swiwel joint sideways offset from center of gokart-->
  <xacro:property name="steering_yoffset" value="${chassi_width/2+0.1}"/>
    <!-- swiwel joint lengthwise offset from center of gokart -->
  <xacro:property name="steering_xoffset" value="${chassi_length/2}"/>
    <!-- swiwel joint z offset -->
  <xacro:property name="steering_zoffset" value="0"/>




  <xacro:property name="steering_body_extension_zoff" value="0"/>
  <xacro:property name="steering_swiwel_length" value="0.05"/>
  <xacro:property name="steering_swiwel_radius" value="0.025"/>
  <xacro:property name="steering_swiwel_extension_length" value="0.03"/>
  <xacro:property name="steering_swiwel_extension_radius" value="0.015"/>
  
  <xacro:property name="steering_turn_max_limit" value="${pi/5}"/>
  <xacro:property name="steering_turn_min_limit" value="${-pi/5}"/>
  
  <!-- Gokart front wing parameters - As of now simplified to a slab -->
  <xacro:property name="gokart_frontwing_width" value="0.8"/>
  <xacro:property name="gokart_frontwing_length" value="0.125"/>
  <xacro:property name="gokart_frontwing_height" value="0.025"/>
  <xacro:property name="gokart_frontwing_body_xoff" value="0.16"/>
  
  <!-- Inertial parameters for chassi dynamics, very simplified -->
  <!-- TODO make the dynamics more accurate and real life accurate, see this as placeholders-->
  <xacro:property name="backwheel_weight" value="4.0"/>
  <xacro:property name="frontwheel_weight" value="1.5"/>
  <xacro:property name="chassi_body_weight" value="50.0"/>
  <xacro:property name="frontwing_weight" value="50.0"/>
  <xacro:property name="front_steering_link_weight" value="0.25"/>

  <!-- Inertial macros -->
   <xacro:include filename="$(find autonomous_platform_robot_description_pkg)/src/description/inertia_macros.xacro"/>
  


  <!-- Robot Base -->
  <link name="chassi_link">
    <visual>
      <geometry>
        <box size="${chassi_length} ${chassi_width} ${chassi_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${chassi_length} ${chassi_width} ${chassi_height}"/>
      </geometry>
    </collision>

    <xacro:inertial_box mass="${chassi_body_weight}" x="${chassi_length}" y="${chassi_width}" z="${chassi_height}">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_box>

    <gazebo reference="chassi_link">
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </gazebo>
  </link>
  
    <!-- Robot Footprint -->
  <link name="base_link"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassi_link"/>
    <origin xyz="0.0 0.0 ${-(backwheel_radius+backwheel_zoff)}" rpy="0 0 0"/>
  </joint>
  
    <!-- macro backwheels -->
  <xacro:macro name="back_wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${backwheel_radius}" length="${backwheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${backwheel_radius}" length="${backwheel_width}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${backwheel_weight}" length="${backwheel_width}" radius="${backwheel_radius}" >
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </xacro:inertial_cylinder>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="chassi_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*backwheel_xoff} ${y_reflect*(chassi_width/2)+y_reflect*backwheel_ygap + y_reflect*backwheel_width/2} ${-backwheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="${prefix}_link">
      <material> Gazebo/DarkGrey </material>
    </gazebo>

  </xacro:macro>

  <!-- Create back wheels -->
  <xacro:back_wheel prefix="back_wheel_left" x_reflect="1" y_reflect="1" />
  <xacro:back_wheel prefix="back_wheel_right" x_reflect="1" y_reflect="-1" />
  
  
  <!-- Front wheel with ackermann steering setup macro -->
  <!-- macro front steering geometry and front wheels i.e define everything once and mirror left and right geometry-->
  <xacro:macro name="front_steering" params="prefix x_reflect y_reflect">
 
     <link name="${prefix}_steering_arm_link">
      <visual>
        <origin xyz="0 ${(steering_arm_length/2)*y_reflect} 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${steering_arm_radius}" length="${steering_arm_length}"/>
        </geometry>
        <material name="arm_link">
          <color rgba="0.6 0.6 0.6 1.0"/>
        </material>
      </visual>

      <collision>
         <origin xyz="0 ${-(steering_arm_length/2)*y_reflect} 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${steering_arm_radius}" length="${steering_arm_length}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${front_steering_link_weight}" length="${steering_arm_length}" radius="${steering_arm_radius}" >
         <origin xyz="0 ${-(steering_arm_length/2)*y_reflect} 0" rpy="${pi/2} 0 0"/>
      </xacro:inertial_cylinder>

      <gazebo reference="${prefix}_steering_arm_link">
        <material> Gazebo/Yellow </material>
      </gazebo>
    </link>

    <!-- link describing the front wheel -->
    <link name="${prefix}_front_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${frontwheel_radius}" length="${frontwheel_width}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${frontwheel_radius}" length="${frontwheel_width}"/>
        </geometry>
      </collision>

      <xacro:inertial_cylinder mass="${frontwheel_weight}" length="${frontwheel_width}" radius="${frontwheel_radius}" >
        <origin xyz="0 ${steering_arm_length} 0" rpy="${pi/2} 0 0"/>
      </xacro:inertial_cylinder>

      <gazebo reference="${prefix}_front_wheel_link">
        <material> Gazebo/Grey </material>
      </gazebo>     
    </link>
    
    
   <!-- joints -->
   <!-- steering extension link is mounted on gokart chassis -->
  <joint name="steering_swiwel_${prefix}_joint" type="revolute">
      <parent link="chassi_link"/>
      <child link="${prefix}_steering_arm_link"/>
      <axis xyz="0 0 1" />
      <limit effort="100" lower="${steering_turn_min_limit }" upper="${steering_turn_max_limit}" velocity="1" />
      <origin xyz="${steering_xoffset} ${steering_yoffset*y_reflect} ${steering_zoffset}" rpy="0 0 0"/>
    </joint>

   <!-- wheel rotatingjoint, wheel is mounted on body extension -->
   <joint name="${prefix}_front_wheel_joint" type="continuous">
      <parent link="${prefix}_steering_arm_link" />
      <child link="${prefix}_front_wheel_link"/>
      <origin xyz="0 ${steering_arm_length*y_reflect+(frontwheel_width/2)*y_reflect} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
    
    

  </xacro:macro>
  

  <!-- Create front wheels with ackermann steering -->
  <xacro:front_steering prefix="left" x_reflect="1" y_reflect="1" />
  <xacro:front_steering prefix="right" x_reflect="1" y_reflect="-1" />
  
  

</robot>